import { load } from 'js-yaml';

const data = load(`
- songId: 'WyiIGEHQP8o'
  title: '빨간 맛'
  artist: '레드벨벳'
  genre: '댄스'
  release: '2017'  
  time: '0:16'
  
- songId: 'lnXXfYA91Y8'
  title: '귀를 기울이면'
  artist: '여자친구'
  genre: '댄스'
  release: '2017'  
  time: '0:40'
  
- songId: 'afxLaQiLu-o'
  title: '비도 오고 그래서'
  artist: '헤이즈'
  genre: '랩/힙합'
  release: '2017'
  time: '0:30'
  
- songId: '8Oz7DG76ibY'
  title: 'DINOSAUR'
  artist: '악동뮤지션'
  genre: '댄스'
  release: '2017'
  time: '0:54'
  
- songId: 'obzb7nlpXZ0'
  title: 'Artist'
  artist: '지코'
  genre: '랩/힙합'
  release: '2017'
  time: '0:09'
  
- songId: '4tdOzlB6I7w'
  title: '신기루'
  artist: '씨잼'
  genre: '랩/힙합'
  release: '2015'
  time: '0:15'
  
- songId: 'NTjGmp5MTV4'
  title: '111%'
  artist: '도끼'
  genre: '랩/힙합'
  release: '2015'
  time: '0:10'
  
- songId: 'vvkWaI91mLM'
  title: '널 너무 모르고'
  artist: '헤이즈'
  genre: '랩/힙합'
  release: '2017'
  time: '0:19'
  
- songId: 'Amq-qlqbjYA'
  title: '마지막처럼'
  artist: '블랙핑크'
  genre: '댄스'
  release: '2017'
  time: '0:17'
  
- songId: 'Ue9NG1hAr78'
  title: '나로 말할 것 같으면'
  artist: '마마무'
  genre: '댄스'
  release: '2017'
  time: '0:09'
  
- songId: 'Z1pGxkXyDvc'
  title: '남이 될 수 있을까'
  artist: '볼빨간사춘기'
  genre: '인디뮤직'
  release: '2017'
  time: '0:12'
  
- songId: 'gSQmYh-kpHY'
  title: '매일 듣는 노래'
  artist: '황치열'
  genre: '발라드'
  release: '2017'
  time: '3:37'
  
- songId: '9kaCAbIXuyg'
  title: '무제'
  artist: 'G-DRAGON'
  genre: '랩/힙합'
  release: '2017'
  time: '0:00'
  
- songId: 'KPhUlyhlUbM'
  title: '처음부터 너와 나'
  artist: '볼빨간사춘기'
  genre: '드라마음악'
  release: '2017'
  time: '0:04'
  
- songId: 'b22Ed7f0D-0'
  title: 'FIVE'
  artist: '에이핑크'
  genre: '댄스'
  release: '2017'
  time: '0:06'
  
- songId: 'JGwWNGJdvx8'
  title: 'SHAPE OF YOU'
  artist: 'Ed Sheeran'
  genre: '팝'
  release: '2017'
  time: '0:16'
  
- songId: 'OwJPPaEyqhI'
  title: 'NEW FACE'
  artist: '싸이'
  genre: '댄스'
  release: '2017'
  time: '0:12'
  
- songId: 'a3JqIwCx8Cs'
  title: '오늘 취하면'
  artist: '수란'
  genre: '알앤비/어반'
  release: '2017'
  time: '0:16'
  
- songId: 'VQtonf1fv_s'
  title: 'SIGNAL'
  artist: '트와이스'
  genre: '댄스'
  release: '2017'
  time: '0:35'
  
- songId: 'd9IxdwEFk1c'
  title: '팔레트'
  artist: '아이유'
  genre: '알앤비/어반'
  release: '2017'
  time: '0:19'
  
- songId: '4tBnF46ybZk'
  title: 'REALLY REALLY'
  artist: 'WINNER'
  genre: '댄스'
  release: '2017'
  time: '0:10'
  
- songId: 'Xvjnoagk6GU'
  title: 'I LUV IT'
  artist: '싸이'
  genre: '댄스'
  release: '2017'
  time: '0:12'
  
- songId: 'KK-1xrOsqXI'
  title: '미치고 싶다'
  artist: '한동근'
  genre: '발라드'
  release: '2017'
  time: '0:04'
  
- songId: 'EHgeGRU3wDI'
  title: "WHY DON'T YOU KNOW"
  artist: '청하'
  genre: '댄스'
  release: '2017'
  time: '0:17'
  
- songId: 'PJlsUe1DUnQ'
  title: 'NEVER'
  artist: '국민의아들'
  genre: '댄스'
  release: '2017'
  time: '0:17'
  
- songId: 'aBSN0g7CdlU'
  title: 'BLUE MOON'
  artist: '효린,창모'
  genre: '댄스'
  release: '2017'
  time: '0:17'
  
- songId: '6rS7OUGXUik'
  title: '첫눈처럼 너에게 가겠다'
  artist: '에일리'
  genre: '발라드'
  release: '2017'
  time: '0:14'
  
- songId: 'KbXV2R_Yd1E'
  title: 'LONELY'
  artist: '씨스타'
  genre: '발라드'
  release: '2017'
  time: '0:13'
  
- songId: '--knPjoSlNE'
  title: 'MARRY ME'
  artist: '마크툽'
  genre: '발라드'
  release: '2014'
  time: '0:28'
  
- songId: 'IdssuxDdqKk'
  title: 'KO KO BOP'
  artist: 'EXO'
  genre: '댄스'
  release: '2017'
  time: '0:13'
  
- songId: 'dMn509ddAkc'
  title: '사랑이 잘'
  artist: '아이유'
  genre: '알앤비/어반'
  release: '2017'
  time: '0:14'
  
- songId: 'Nv5_uvyqI9s'
  title: '맞지?'
  artist: '언니쓰'
  genre: '댄스'
  release: '2017'
  time: '0:58'
  
- songId: 'b1kQvZhQ6_M'
  title: '좋니'
  artist: '윤종신'
  genre: '발라드'
  release: '2017'
  time: '0:06'
  
- songId: 'OJ6alJj1hQw'
  title: '아침에'
  artist: '양홍원'
  genre: '랩/힙합'
  release: '2017'
  time: '0:18'
  
- songId: 'y5MAgMVwfFs'
  title: '좋다고 말해'
  artist: '볼빨간사춘기'
  genre: '인디뮤직'
  release: '2016'
  time: '0:13'
  
- songId: 'ywwU5ka1fBs'
  title: '아름다워'
  artist: '창모'
  genre: '랩/힙합'
  release: '2016'
  time: '0:21'
  
- songId: 'gnLwCb8Cz7I'
  title: '사랑앓이'
  artist: 'FTISLAND'
  genre: '발라드'
  release: '2007'
  time: '0:18'
  
- songId: 'pC6tPEaAiYU'
  title: 'TOMBOY'
  artist: '혁오'
  genre: '락'
  release: '2017'
  time: '0:04'
  
- songId: '8A2t_tAjMz8'
  title: 'KNOCK KNOCK'
  artist: '트와이스'
  genre: '댄스'
  release: '2017'
  time: '0:14'
  
- songId: 'iLlLLBuuvVU'
  title: '나만 안되는 연애'
  artist: '볼빨간사춘기'
  genre: '인디뮤직'
  release: '2016'
  time: '0:15'
  
- songId: 'lT7Q93fy1us'
  title: 'ALL I WANNA DO'
  artist: '박재범'
  genre: '알앤비/어반'
  release: '2016'
  time: '0:09'
  
- songId: '9U8uA702xrE'
  title: '우주를 줄게'
  artist: '볼빨간사춘기'
  genre: '인디뮤직'
  release: '2016'
  time: '0:06'
  
- songId: '9pdj4iJD08s'
  title: '불장난'
  artist: '블랙핑크'
  genre: '댄스'
  release: '2016'
  time: '0:21'
  
- songId: 'OQu1AsKHH4Q'
  title: '돌아오지마'
  artist: '헤이즈'
  genre: '랩/힙합'
  release: '2016'
  time: '0:20'
  
- songId: 'xEeFrLSkMm8'
  title: '봄날'
  artist: '방탄소년단'
  genre: '랩/힙합'
  release: '2016'
  time: '0:47'
  
- songId: 'PT2_F-1esPk'
  title: 'CLOSER'
  artist: 'The Chainsmokers'
  genre: '일렉트로니카'
  release: '2016'
  time: '0:10'
  
- songId: 'GYX5QOVkHxc'
  title: 'FANXY CHILD'
  artist: '지코'
  genre: '랩/힙합'
  release: '2017'
  time: '0:06'
  
- songId: 'Nkbz1te_lqI'
  title: 'OUTSIDE'
  artist: 'CRUSH'
  genre: '알앤비/어반'
  release: '2017'
  time: '0:41'
  
- songId: 'eelfrHtmk68'
  title: 'D'
  artist: 'DEAN'
  genre: '알앤비/어반'
  release: '2016'
  time: '0:22'
  
- songId: '1xVB4UajjgY'
  title: '먹구름'
  artist: '헤이즈'
  genre: '랩/힙합'
  release: '2017'
  time: '0:18'
  
- songId: 'wxQZ48TgqZk'
  title: '부담이 돼'
  artist: '정키'
  genre: '발라드'
  release: '2017'
  time: '0:33'
  
- songId: 'OmjN_b07syo'
  title: '오빠야'
  artist: '신현희와김루트'
  genre: '인디뮤직'
  release: '2015'
  time: '0:03'
  
- songId: '4Les0OrRuZ0'
  title: '아재개그'
  artist: '마마무'
  genre: '댄스'
  release: '2017'
  time: '0:13' 
  
- songId: 'Y9XXGztRM4Y'
  title: '여왕의 기사'
  artist: '뉴이스트'
  genre: '댄스'
  release: '2017'
  time: '0:28'

- songId: 'YT3Zz1iIzOI'
  title: '있잖아'
  artist: '폴킴'
  genre: '드라마'
  release: '2017'
  time: '0:13'

- songId: 'hmE9f-TEutc'
  title: '피 땀 눈물'
  artist: '방탄소년단'
  genre: '랩/힙합'
  release: '2016'
  time: '0:56'
  
- songId: 'EVaV7AwqBWg'
  title: '에너제틱'
  artist: '워너원'
  genre: '댄스'
  release: '2017'
  time: '0:28'

- songId: '0VKcLPdY9lI'
  title: '시간을 달려서'
  artist: '여자친구'
  genre: '댄스'
  release: '2016'
  time: '0:31'

- songId: 'J0h8-OTC38I'
  title: 'ROOKIE'
  artist: '레드벨벳'
  genre: '댄스'
  release: '2017'
  time: '0:16'

- songId: 'glXgSSOKlls'
  title: 'ICE CREAM CAKE'
  artist: '레드벨벳'
  genre: '댄스'
  release: '2015'
  time: '0:08'

- songId: 'XGdbaEDVWp0'
  title: 'DUMB DUMB'
  artist: '레드벨벳'
  genre: '댄스'
  release: '2015'
  time: '0:00'

- songId: 'XGdbaEDVWp0'
  title: 'DUMB DUMB'
  artist: '레드벨벳'
  genre: '댄스'
  release: '2015'
  time: '0:00'

- songId: 'wEQpfil0IYA'
  title: '오랜 날 오랜 밤'
  artist: '악동뮤지션'
  genre: '발라드'
  release: '2017'
  time: '0:17'

- songId: 'BiorIyrjTHc'
  title: 'PICK ME'
  artist: 'PRODUCE 101'
  genre: '일렉트로니카'
  release: '2015'
  time: '0:46'

- songId: 'iIPH8LFYFRk'
  title: '에라 모르겠다'
  artist: '빅뱅'
  genre: '일렉트로니카'
  release: '2016'
  time: '0:23'

- songId: '5JbVVlqrreE'
  title: '나비잠'
  artist: '김희철X민경훈'
  genre: '락'
  release: '2016'
  time: '0:19'

- songId: 'L-2M_-QLs8k'
  title: '내가 저지른 사랑'
  artist: '임창정'
  genre: '발라드'
  release: '2016'
  time: '0:11'

- songId: 'EjHAgoN2KtU'
  title: '너였다면'
  artist: '정승환'
  genre: '발라드'
  release: '2016'
  time: '0:08'

- songId: 'dISNgvVpWlo'
  title: '휘파람'
  artist: '블랙핑크'
  genre: '랩/힙합'
  release: '2016'
  time: '0:22'

- songId: 'WbhK3wMXluE'
  title: 'BYE BYE MY BLUE'
  artist: '백예린'
  genre: '알앤비/소울'
  release: '2016'
  time: '0:22'

- songId: 'cQuqs2LrXbo'
  title: '우주를 건너'
  artist: '백예린'
  genre: '알앤비/소울'
  release: '2015'
  time: '0:09'

- songId: 'r6TRytnpaYs'
  title: '아주 오래된 기억'
  artist: '백예린'
  genre: '드라마'
  release: '2017'
  time: '0:09'

- songId: 'x815A21RIto'
  title: '이럴거면 그러지말지'
  artist: '백아연'
  genre: '발라드'
  release: '2015'
  time: '0:01'

- songId: 'BbQG-S4mU0U'
  title: '쏘쏘'
  artist: '백아연'
  genre: '발라드'
  release: '2016'
  time: '0:04'

- songId: 'TghSCDClIYU'
  title: '그냥 한 번'
  artist: '백아연'
  genre: '발라드'
  release: '2016'
  time: '0:00'

- songId: 'rUbq_IXBaYg'
  title: '광화문에서'
  artist: '규현'
  genre: '발라드'
  release: '2014'
  time: '0:15'

- songId: 'pLuETPoCKRo'
  title: '어쩌면 나'
  artist: '로이킴'
  genre: '드라마'
  release: '2016'
  time: '0:25'

- songId: 'pLuETPoCKRo'
  title: '어쩌면 나'
  artist: '로이킴'
  genre: '드라마'
  release: '2016'
  time: '0:25'

- songId: 'eHir_vB1RUI'
  title: 'RAIN'
  artist: '태연'
  genre: '발라드'
  release: '2016'
  time: '0:13'

`);


export const loadData = () => {
    console.log(data);
}